-- Seed the volunteer_opportunities catalog with real, currently-operating
-- organizations near each real NAC venue (see src/app/trips/nacs.ts for the
-- matching NAC_OPTIONS entries). Researched directly from each
-- organization's own site as of Aug 2026. Distances are approximate
-- driving-distance estimates, not geocoded. Where an organization does not
-- publish a fixed shift length, age requirement, or minor policy, that is
-- stated honestly rather than invented. signup_url is the natural dedup
-- key (see the earlier unique-constraint migration), so this insert is
-- safe to re-run.

insert into public.volunteer_opportunities
  (event_name, organization, event_date_time, duration, address, zip, city_state, signup_url, source_platform, walk_in_or_approval_required, age_requirement, minor_policy, nac_event, description, distance_from_venue)
values
  -- October 2026 NAC — Orlando, FL (Orange County Convention Center)
  ('Warehouse Sorting & Packing Shift', 'Second Harvest Food Bank of Central Florida', 'Recurring shifts available Oct 9-12, 2026 -- sign up for an open slot online', 'Varies by shift -- select an available time slot when signing up', '411 Mercy Drive', '32805', 'Orlando, FL', 'https://feedhopenow.org/get-involved/volunteer/', 'Organization Website', 'Online signup required; select a shift from their volunteer calendar', 'Volunteers must be at least 10 years old', 'Ages 10-15 must be accompanied by a chaperone (18+); ages 16+ may volunteer independently', 'October 2026 NAC', 'Sort and pack donated food -- including Power Packs, Senior Food Boxes, and Emergency Boxes -- to help provide meals to families, children, and seniors facing hunger in Central Florida.', 'About 11 miles from Orange County Convention Center (approximate driving distance)'),
  ('Home Build Volunteer Day', 'Habitat for Humanity Greater Orlando & Osceola County', 'Recurring build days available around Oct 9-12, 2026 -- sign up for an open slot online', 'Varies -- not specified on their site', '4116 Silver Star Road', '32808', 'Orlando, FL', 'https://habitatorlando.org/volunteer/', 'Organization Website', 'Online registration required before arriving at a build site', 'All volunteers must be at least 16 years old, no exceptions', 'Ages 16-17 may be on-site but cannot work on ladders or use power tools; no volunteers under 16 permitted on build sites', 'October 2026 NAC', 'Help construct affordable homes -- framing walls, siding, drywall, caulking, priming, painting, and landscaping -- alongside trained site supervisors. No construction experience needed.', 'About 12 miles from Orange County Convention Center (approximate driving distance)'),
  ('Volunteer Portal Opportunities', 'Coalition for the Homeless of Central Florida', 'Ongoing opportunities around Oct 9-12, 2026 -- browse and select a slot via their volunteer portal', 'Not specified on their site', '18 North Terry Avenue', '32801', 'Orlando, FL', 'https://www.centralfloridahomeless.org/take-action', 'Organization Website', 'Registration through their volunteer portal (coalitionvolunteer.org) required', 'Must be at least 18 years old to volunteer independently', 'Minors ages 16-17 may volunteer alongside an adult who is at least 21 years old', 'October 2026 NAC', 'Support men, women, and families experiencing homelessness in Central Florida through a range of opportunities coordinated via the Coalition''s volunteer portal.', 'About 13 miles from Orange County Convention Center (approximate driving distance)'),
  ('Guest Family Support & Hospitality Shift', 'Ronald McDonald House Charities of Central Florida', 'Recurring shifts around Oct 9-12, 2026 -- sign up for an open slot online', 'Not specified for individual shifts on their site', '1030 N. Orange Avenue, Suite 105', '32801', 'Orlando, FL', 'https://rmhccf.org/get-involved/volunteer/', 'Organization Website', 'Online application required; some roles (e.g. In-House Volunteer) require a background check', 'Ages 18+ required for In-House and Ambassador Volunteer roles; other programs (Share-A-Meal, Baking Buddies, Brunch, Family Wellness) list no stated minimum age', 'Groups with minors must include at least one supervising adult; no specific minimum age given for minors in a group', 'October 2026 NAC', 'Support families staying near their hospitalized children through donation sorting, restocking, light housekeeping, meal preparation, and hospitality programs like Share-A-Meal and Baking Buddies.', 'About 13 miles from Orange County Convention Center (approximate driving distance)'),

  -- November 2026 NAC — Columbus, OH (venue not yet announced)
  ('Food Sorting & Packing Shift', 'Mid-Ohio Food Collective', 'Recurring shifts around Nov 20-23, 2026 -- sign up via their volunteer hub', 'Not specified on their main volunteer page', '3960 Brookham Drive', '43123', 'Grove City, OH', 'https://mofc.org/get-involved/volunteer/', 'Organization Website', 'Online signup required via mofb.volunteerhub.com', 'Varies by role -- Mid-Ohio Market at Gantz requires ages 16+; the farm/garden allows 14+ with a parent or guardian', 'Ages 11-15 must be accompanied by an adult at the Market at Gantz; farm/garden allows 14+ with a parent or guardian', 'November 2026 NAC', 'Sort and pack food, staff Mid-Ohio Markets, help in the community garden/farm, or prep meals in the Mid-Ohio Kitchen to support Central Ohio families facing hunger.', 'About 13 miles from downtown Columbus (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('ReStore or Home Build Volunteer Shift', 'Habitat for Humanity MidOhio', 'Build sites run Tuesday-Saturday; ReStore open Monday-Saturday -- sign up for an available shift around Nov 20-23, 2026', 'Construction shifts run 8:30am-3:30pm; evening crew shifts most Wed/Thu 5:30-8:00pm; ReStore shifts range from a few hours to a full day (9am-5pm)', '3140 Westerville Rd (ReStore); 6665 Busch Blvd (admin office)', '43224', 'Columbus, OH', 'https://www.habitatmidohio.org/get-involved/volunteer/overview.html', 'Organization Website', 'Online registration and an electronic waiver (via SmartWaiver) required before a shift', 'Must be at least 16 years old for both build sites and ReStores', 'Under-18 volunteers must be accompanied by an adult 21 or older, at a five-to-one youth-to-adult ratio; youth cannot operate power tools or work at heights above six feet', 'November 2026 NAC', 'Work a home construction build site (framing, siding, painting, and more -- no experience required) or help in a ReStore preparing donations, merchandising, and assisting customers.', 'About 8 miles from downtown Columbus (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('Day Services & Donations Support Shift', 'The Open Shelter', 'Ongoing opportunities around Nov 20-23, 2026 -- contact them directly to schedule', 'Not specified on their site', '1037 Parsons Ave.', '43206', 'Columbus, OH', 'https://theopenshelter.org/', 'Organization Website', 'Not specified on their site -- contact 614-222-2885 or tosi@theopenshelter.org to arrange', 'Not specified on their site', 'Not specified on their site -- confirm directly before bringing a minor', 'November 2026 NAC', 'Help prepare and serve food, accept and sort donations, organize the Material Assistance Room, and support facility upkeep for people experiencing homelessness in Central Ohio.', 'About 2 miles from downtown Columbus (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('Meal Delivery or Kitchen Prep Shift', 'LifeCare Alliance (Meals on Wheels Columbus)', 'Recurring weekday shifts around Nov 20-23, 2026 -- sign up online', 'Kitchen and pet-food-sorting roles run about 1-2 hours; meal delivery routes take about 1 hour', '1699 W. Mound St.', '43223', 'Columbus, OH', 'https://www.lifecarealliance.org/volunteer/', 'Organization Website', 'Online signup required; meal delivery requires a valid driver''s license', 'Not specified generally; meal delivery implies an adult driver', 'Not specified on their site', 'November 2026 NAC', 'Deliver meals to homebound Columbus residents, help prep and package food in the kitchen, or assist with pet food delivery and other support programs.', 'About 2 miles from downtown Columbus (venue not yet announced by USA Fencing; distance measured from downtown)'),

  -- January 2027 Junior Olympics & Para NAC — Oklahoma City, OK (venue not yet announced)
  ('Donation Resource Center & Meal Prep Shift', 'City Rescue Mission', 'Opportunities run 9am-6pm daily around Jan 8-11, 2027 -- register 1-2 days ahead via their online calendar', 'Not specified as a fixed length -- shifts scheduled via their online calendar (9am-6pm window)', '800 W. California Ave.', '73106', 'Oklahoma City, OK', 'https://cityrescue.org/volunteer/', 'Organization Website', 'Online registration required, closing 1-2 days before an event', 'No age requirement stated', 'Minors must be accompanied by an adult; minors may serve in all areas except Food Prep', 'January 2027 Junior Olympics & Para NAC', 'Support the Donation Resource Center and help with meal preparation for people experiencing homelessness; family volunteering is encouraged.', 'About 1 mile from downtown Oklahoma City (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('Day Shelter Support Shift', 'Homeless Alliance', 'Ongoing opportunities around Jan 8-11, 2027 -- sign up via their volunteer portal', 'Not specified on their site (Day Shelter itself operates 7am-3pm daily)', '1724 NW 4th St.', '73106', 'Oklahoma City, OK', 'https://www.homelessalliance.org/get-involved', 'Organization Website', 'Online registration required via their volunteer portal', 'Not specified on their site', 'Not specified on their site -- confirm directly before bringing a minor', 'January 2027 Junior Olympics & Para NAC', 'Support the Westtown Homeless Resource Campus Day Shelter, which serves about 300 people a day with breakfast, lunch, showers, and access to phones, computers, and mail.', 'About 1-2 miles from downtown Oklahoma City (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('Food Sorting & Packing Shift', 'Regional Food Bank of Oklahoma', 'Recurring shifts around Jan 8-11, 2027 -- sign up online', 'Not specified on their site', '3355 S. Purdue Ave.', '73179', 'Oklahoma City, OK', 'https://www.regionalfoodbank.org/volunteer/individual/', 'Organization Website', 'Online signup required', 'Minimum age of 8 years old (per organization FAQ; recommend confirming directly)', 'Volunteers under 16 must be accompanied by an adult', 'January 2027 Junior Olympics & Para NAC', 'Sort, pack, and prepare food for programs like the Food for Kids Backpack Program, including bread, produce, and canned goods at the Volunteer Center.', 'About 8-9 miles from downtown Oklahoma City (venue not yet announced by USA Fencing; distance measured from downtown)'),
  ('Meal Delivery Shift', 'Meals on Wheels Oklahoma City (Ending Hunger OKC)', 'Recurring weekday shifts around Jan 8-11, 2027 -- sign up online, background check required', 'Not specified on their site', '222 NW 15th St.', '73103', 'Oklahoma City, OK', 'https://www.mealsonwheelsokc.org/volunteers', 'Organization Website', 'Online application and background check required before scheduling', 'No strict minimum age stated', 'Volunteers under 18 must be accompanied by an adult', 'January 2027 Junior Olympics & Para NAC', 'Deliver meals to homebound seniors across Oklahoma County, often providing the only friendly visit a senior sees that day.', 'About 1-2 miles from downtown Oklahoma City (venue not yet announced by USA Fencing; distance measured from downtown)'),

  -- April 2027 NAC — Cincinnati, OH (First Financial Center)
  ('Warehouse Sorting & Packing Shift', 'Freestore Foodbank', 'Recurring morning (9-11:30am) and afternoon (1-3:30pm) shifts around Apr 16-19, 2027 -- sign up online', 'About 2.5 hours per shift (morning or afternoon)', '3401 Rosenthal Way', '45204', 'Cincinnati, OH', 'https://freestorefoodbank.org/volunteers/', 'Organization Website', 'Online registration required', 'Community Resource & Distribution Center requires age 13+; Customer Connection Center requires age 16+', 'Volunteers under 16 must be accompanied by an adult; ages 13-15 must be accompanied by an adult at the distribution center; minors must submit a signed Parent Consent form before arrival', 'April 2027 NAC', 'Sort and pack food -- including Power Packs, Senior Food Boxes, Emergency Boxes, and Summer Kid Boxes -- or help at the retail-style Customer Connection Center pantry.', 'About 1 mile from First Financial Center (Customer Connection Center location)'),
  ('ReStore or Home Build Volunteer Shift', 'Habitat for Humanity of Greater Cincinnati', 'Typical construction shift runs 8:30am-4pm around Apr 16-19, 2027 -- sign up online', 'A typical construction shift is 8:30am to 4pm; ReStore shift length not specified', '4910 Para Drive', '45237', 'Cincinnati, OH', 'https://www.habitatcincinnati.org/individual-volunteers', 'Organization Website', 'Online registration and a signed waiver required for volunteers under 18', 'Ages 18+ may volunteer independently; ages 16-17 may volunteer independently at the ReStore or with a parent/guardian (21+) at a construction site; ages 14-15 may volunteer at the ReStore only with adult supervision; under 14 not permitted', 'Groups with minors ages 14-17 require at least one adult (21+) per five minors; volunteers under 18 need a signed parent/guardian waiver', 'April 2027 NAC', 'Work a home construction site alongside trained staff, or help in the ReStore unloading, cleaning, and shelving donations and assisting customers.', 'About 7-8 miles from First Financial Center (approximate driving distance)'),
  ('Food Pantry or Thrift Store Volunteer Shift', 'Society of St. Vincent de Paul, Cincinnati District Council', 'Ongoing opportunities around Apr 16-19, 2027 -- contact them to arrange a shift', 'Not specified on their site', '1125 William L. Mallory, Sr. St.', '45214', 'Cincinnati, OH', 'https://svdpcincinnati.org/volunteer/volunteer-opportunities/', 'Organization Website', 'Not specified on their site -- contact them directly to arrange', 'Food pantry volunteers must be over the age of 14; no age minimum stated for thrift store, call center, or home visit roles', 'Not specified beyond the pantry age-14 minimum -- confirm directly before bringing a minor', 'April 2027 NAC', 'Stock shelves and sort donations at a food pantry, sort and merchandise donations at a thrift store, join home visits to neighbors in need, or help callers apply for aid.', 'About 1.5 miles from First Financial Center'),
  ('Warehouse Supply Sorting Shift', 'Matthew 25: Ministries', 'Weekday walk-in hours 9am-4pm (Mon-Fri) and shorter Saturday slots (1-3pm) around Apr 16-19, 2027 -- confirm ahead by phone', 'About 2 hours for weekend slots; weekday walk-in window is 9am-4pm', '11060 Kenwood Road', '45242', 'Cincinnati, OH', 'https://m25m.org/help/volunteering/', 'Organization Website', 'Walk-ins accepted during posted hours; recommend calling (513) 793-6256 ahead to confirm', 'Not independently verified -- sources conflict; recommend confirming directly (16+ suggested by a third-party volunteer listing)', 'Not independently verified -- recommend confirming directly by phone or email before bringing a minor', 'April 2027 NAC', 'Evaluate, sort, and process donated supplies -- clothing, shoes, hygiene kits, paint, and sanitary supplies -- for domestic and international disaster relief and humanitarian aid.', 'About 15-16 miles from First Financial Center (approximate driving distance)')
on conflict (signup_url) do nothing;
