-- Reconcile the externally-imported catalog rows with this app's real,
-- dated NAC names, delete 2 confirmed duplicates of hand-researched rows,
-- and populate real geocoded distance_miles (+ human-readable
-- distance_from_venue text) for every row in the 3 NAC groups that
-- actually match a NAC this app supports (October 2026 / November 2026 /
-- January 2027 JO). Rows with no verifiable street address are marked
-- distance-unknown rather than guessed. The unmatched external groups
-- (Richmond VA / Las Vegas / Portland -- none of which correspond to a
-- NAC this app lists) are intentionally left untouched.

update public.volunteer_opportunities set nac_event = 'October 2026 NAC' where nac_event = 'October NAC';
update public.volunteer_opportunities set nac_event = 'November 2026 NAC' where nac_event = 'November NAC';
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC' where nac_event = 'January JO';

-- Confirmed duplicates of hand-researched rows (same org, same address) -- the
-- hand-researched row already has the fuller data (real signup URL, description,
-- age/minor policy), so the sparser external copy is removed.
delete from public.volunteer_opportunities where id = 'a0c18846-2dd4-4217-b793-7459af2794af';
delete from public.volunteer_opportunities where id = '514e8684-6b79-42ca-9781-1d70afbe89f8';

-- Recomputed precise geocoded distances for the 16 hand-researched rows
-- (supersedes the earlier rough hand-written estimates).
update public.volunteer_opportunities set distance_miles = 3.6, distance_from_venue = '3.6 miles from First Financial Center' where id = 'd3df7328-03e4-4370-aaa7-73babc178646'; -- Freestore Foodbank (keep)
update public.volunteer_opportunities set distance_miles = 5.4, distance_from_venue = '5.4 miles from First Financial Center' where id = '507f9f81-68f4-47f7-b784-86bee88d34d0'; -- Habitat for Humanity of Greater Cincinnati (keep)
update public.volunteer_opportunities set distance_miles = 8.2, distance_from_venue = '8.2 miles from First Financial Center' where id = '8c8c5701-1b3f-498d-9db6-b54908d10232'; -- Matthew 25: Ministries (keep)
update public.volunteer_opportunities set distance_miles = 1.6, distance_from_venue = '1.6 miles from First Financial Center' where id = '895895d3-3d11-4713-b958-b43d78386b2c'; -- Society of St. Vincent de Paul, Cincinnati District Council (keep)
update public.volunteer_opportunities set distance_miles = 0.7, distance_from_venue = '0.7 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'caea07be-71f0-44b7-8871-0a651f670284'; -- City Rescue Mission (keep)
update public.volunteer_opportunities set distance_miles = 1.8, distance_from_venue = '1.8 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '065afe7d-5492-433c-b705-8165a860bcc4'; -- Homeless Alliance (keep)
update public.volunteer_opportunities set distance_miles = 1.6, distance_from_venue = '1.6 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '13e04c68-cfac-4b71-9481-aa1f16d9deb0'; -- Meals on Wheels Oklahoma City (Ending Hunger OKC) (keep)
update public.volunteer_opportunities set distance_miles = 5.9, distance_from_venue = '5.9 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '2d830143-67b1-4d3f-8849-dac3e1447bb0'; -- Regional Food Bank of Oklahoma (keep)
update public.volunteer_opportunities set distance_miles = 3.9, distance_from_venue = '3.9 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'fdada24c-81f3-4a66-8f4c-d255ed40d296'; -- Habitat for Humanity MidOhio (keep)
update public.volunteer_opportunities set distance_miles = 4.0, distance_from_venue = '4.0 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'c0894699-cb83-47d1-ba47-328528d4dd5b'; -- LifeCare Alliance (Meals on Wheels Columbus) (keep)
update public.volunteer_opportunities set distance_miles = 6.7, distance_from_venue = '6.7 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '1e4caffc-7396-49a2-bad9-2321a442090b'; -- Mid-Ohio Food Collective (keep)
update public.volunteer_opportunities set distance_miles = 2.2, distance_from_venue = '2.2 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'c85b415d-52b5-4464-803d-3d1d50da9e2d'; -- The Open Shelter (keep)
update public.volunteer_opportunities set distance_miles = 9.3, distance_from_venue = '9.3 miles from Orange County Convention Center' where id = 'a39a98b0-7992-452c-b215-8de1ce612d60'; -- Coalition for the Homeless of Central Florida (keep)
update public.volunteer_opportunities set distance_miles = 11.0, distance_from_venue = '11.0 miles from Orange County Convention Center' where id = '3ac3f518-db3f-4e4d-8a6b-3acd59d60994'; -- Habitat for Humanity Greater Orlando & Osceola County (DROP >10mi)
update public.volunteer_opportunities set distance_miles = 10.6, distance_from_venue = '10.6 miles from Orange County Convention Center' where id = '19de3d5e-431f-40a8-8b76-37f3d27ae059'; -- Ronald McDonald House Charities of Central Florida (DROP >10mi)
update public.volunteer_opportunities set distance_miles = 8.7, distance_from_venue = '8.7 miles from Orange County Convention Center' where id = '2f1024ec-ceb2-4577-901a-12aad6a78bbe'; -- Second Harvest Food Bank of Central Florida (keep)

-- Externally-imported rows with a real street address: renamed to the correct
-- dated NAC, given a real geocoded distance, and had their misplaced
-- "X Miles" text (which was never real date/time data) cleared where present.
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 16.9, distance_from_venue = '16.9 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '6576cfcd-94be-4779-9d54-b370ed0bf295'; -- Aging Services, Inc. (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 28.6, distance_from_venue = '28.6 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'f52b3b85-c4c7-4ace-aaad-fa9ffd4e1ced'; -- Cheyenne-Arapaho Tribes of Oklahoma (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 13.4, distance_from_venue = '13.4 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'd609fe81-f3c1-427d-930e-1e3e012a63fa'; -- Edmond Mobile Meals, Inc. (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 67.8, distance_from_venue = '67.8 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'd8cb3b9d-4e15-480c-b8fa-55067a711c2e'; -- Enid Habitat for Humanity (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 105.0, distance_from_venue = '105.0 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '305f6bb1-6fd4-488f-b3b6-bc6932139b2b'; -- Meals on Wheels of Metro Tulsa, Inc. (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 16.9, distance_from_venue = '16.9 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'b9b22e98-401b-4359-9966-eb82e8444e98'; -- Meals on Wheels of Norman (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 5.6, distance_from_venue = '5.6 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'e4b358e9-7375-4e20-901f-b7ff3f161fb0'; -- Oklahoma County Senior Nutrition Program (keep)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 19.0, distance_from_venue = '19.0 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'f95477fb-bfb3-4395-9b41-8970814a0737'; -- Oklahoma County Senior Nutrition Program – Harrah (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 16.8, distance_from_venue = '16.8 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = 'fd5b2cc4-70e5-4847-b76d-972b898e2332'; -- Rose Rock Habitat for Humanity (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_miles = 51.4, distance_from_venue = '51.4 miles from downtown Oklahoma City (venue not yet announced by USA Fencing)' where id = '1d692880-92fd-47d9-8a9d-6dd4dea5ab74'; -- Stillwater Habitat for Humanity (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 43.7, distance_from_venue = '43.7 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '6be78236-15e8-48d8-99ec-9a6500eedea8'; -- Buckeye Ridge Habitat for Humanity (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 0.7, distance_from_venue = '0.7 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '1ab1120e-936d-4fbe-9631-6ae7527fc433'; -- Central Ohio Area Agency on Aging (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 2.3, distance_from_venue = '2.3 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '3bb096af-3f1d-4746-b72a-abd8ce113d36'; -- Greta Lewis Lupus Foundation (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 40.9, distance_from_venue = '40.9 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '679bc2ea-e021-4253-9e04-88170b62fbe9'; -- Habitat for Humanity of Champaign County, Ohio (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 22.5, distance_from_venue = '22.5 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '04a74531-3ea4-4454-96ff-70d6ad5f2640'; -- Habitat for Humanity of Delaware & Union Counties (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 2.3, distance_from_venue = '2.3 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'd70fd52b-aaf1-4326-bf16-1f1b80193581'; -- Healing Minds Through Design (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 34.2, distance_from_venue = '34.2 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '65386867-046b-4ff3-a581-3cf1909a3303'; -- Licking County Aging Partners (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 26.7, distance_from_venue = '26.7 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '4adb7e99-0be0-44dc-b0dd-10d7757c378d'; -- Meals on Wheels Fairfield County (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 26.3, distance_from_venue = '26.3 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '54c90c03-154e-41d8-93e7-b850ee7e8910'; -- Memorial Hospital of Union County (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 25.8, distance_from_venue = '25.8 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '52e64877-064e-4ab4-b2e3-f6854952c2f2'; -- Pickaway County Commission on Aging (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 8.8, distance_from_venue = '8.8 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'e61ddaec-dc8d-4268-815a-0adfae9f5d1f'; -- Senior Independence (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 5.3, distance_from_venue = '5.3 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '44246f65-5f15-4f62-b62e-786307c61a62'; -- Simply EZ Home Delivered Meals (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 18.7, distance_from_venue = '18.7 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = 'b2c2f42d-f425-47f4-a327-bdf0c063aae0'; -- SourcePoint (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 39.8, distance_from_venue = '39.8 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '6111c1d5-4c79-41e0-b1b5-24489d208d73'; -- The Station Break (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 6.0, distance_from_venue = '6.0 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '3aab5a0e-aa20-400e-a728-31cb32b0f24c'; -- Transportation Security Administration CMH K9 (keep)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 43.2, distance_from_venue = '43.2 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '06843114-cfbe-4235-8970-4ff304962ce9'; -- United Senior Services (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_miles = 3.9, distance_from_venue = '3.9 miles from downtown Columbus (venue not yet announced by USA Fencing)' where id = '84416adf-3df2-4f87-824e-80cffad08ff1'; -- Wexner Heritage Village (keep)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 20.4, distance_from_venue = '20.4 miles from Orange County Convention Center' where id = '1e651217-6b3f-44ba-9484-a20142a2201d'; -- First United Methodist Church (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 17.2, distance_from_venue = '17.2 miles from Orange County Convention Center' where id = 'f12f0019-32d8-4834-a572-0da412ce0bb1'; -- Habitat for Humanity of Seminole County and Greater Apopka, Florida (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 13.5, distance_from_venue = '13.5 miles from Orange County Convention Center' where id = '5499f0cc-7c08-4687-ab95-af62a7a9ef26'; -- Habitat for Humanity of Winter Park/Maitland (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 32.1, distance_from_venue = '32.1 miles from Orange County Convention Center' where id = '3fca15df-459a-4661-8186-d079718ff4aa'; -- Meals on Wheels of Polk County (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 11.6, distance_from_venue = '11.6 miles from Orange County Convention Center' where id = '91699f9a-4069-4be6-9af7-d311f7aa6dd8'; -- Meals on Wheels Osceola (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 29.1, distance_from_venue = '29.1 miles from Orange County Convention Center' where id = 'a0dfc982-860f-4cce-a29c-8233df88e92f'; -- Meals On Wheels, Etc. (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 11.6, distance_from_venue = '11.6 miles from Orange County Convention Center' where id = 'e20ad4d9-acf7-4763-a758-ea51d8630766'; -- Senior Resource Alliance, the AAA of Central Florida (DROP >10mi)
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_miles = 5.4, distance_from_venue = '5.4 miles from Orange County Convention Center' where id = '71686159-02b3-48d8-8cf6-0c674979bb9f'; -- Seniors First, Inc. (keep)

-- Externally-imported rows with no verifiable street address (only a city name,
-- or an address that couldn't be geocoded, e.g. a PO Box) -- kept visible per
-- request, but marked as distance-unknown rather than guessed.
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '2f5efbeb-8dee-4395-9eef-a92290b09215'; -- Alenza Wellness Community Outreach
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '1e379b3c-2db3-49e5-af8e-cb3a8fc47990'; -- American Cancer Society
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '93bdcf24-f6b1-45ab-8f75-06adf4cb6678'; -- Big Brothers Big Sisters of Oklahoma Inc.
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'c6ae2b10-c1be-46a9-acf0-5d348f6478d5'; -- Bodies Race Company
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'f9229aec-5d3b-4e7e-84d5-8802b2cdef9e'; -- Citizens'' Climate Lobby
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '18dc36b6-2994-4c88-9d07-bbb6dab269d7'; -- Good Shepherd Hospice OKC Metro
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '0139dc2a-89e3-46cb-a275-98dc2797142a'; -- GOODMAN HOMES INC
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '193c3052-97a8-49e7-b6a7-362efbae7b63'; -- Healing Minds Through Design
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'f18d1c86-b0ad-4273-81ec-0f2c6117d82f'; -- Helping Every Life Possible
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '970dce8f-f520-45ae-8256-5f022ea1a5b7'; -- Helping Every Life Possible
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '353f661d-8c43-4488-b42d-eaf194595fb5'; -- International Cultural Exchange Services (ICES)
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '83b43ad6-410e-4a9f-b94c-280286ed6201'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '78e5c994-6c12-4025-afa8-4460fdb76912'; -- MUSICLINK FOUNDATION
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '37b84645-afac-47ec-a13e-fb790f727895'; -- MYRIAD GARDENS FOUNDATION
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '9ac1e736-7b47-438a-a155-8328e0a785f2'; -- MYRIAD GARDENS FOUNDATION
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '83640b97-462e-48f9-8834-4f19c0f43bbd'; -- Oklahoma City Indian Clinic
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '06759c63-01f0-4afb-b95e-d926d443f6c4'; -- Simply United Together Global
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '26e60936-fd13-42aa-a0c9-b20ffc921bbf'; -- Sisu Youth Services
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '606687e0-1dfa-4830-9e21-9a8f4ee1c500'; -- Skyline
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '654142b8-fac4-4e20-981d-3f4d8a9403ae'; -- Weatherford Community Habitat for Humanity
update public.volunteer_opportunities set nac_event = 'January 2027 Junior Olympics & Para NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'ccafcbcf-72bc-43c6-8e26-ebba7e388d07'; -- Yukon Mobile Meals, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'dc412641-8a19-43b1-a515-d06757182db3'; -- American Cancer Society | Central Southwest Ohio
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '6131ba55-6d0d-41ab-a595-042d2361a357'; -- American Youth Literacy Foundation
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '39ed5a5c-c929-4d3b-9ae9-3bf1c5a93066'; -- Centerburg Senior Services, Inc.
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '4b1eb737-db82-4e8f-a085-8528f49cc84e'; -- COLUMBUS OHIO FIRE FIGHTERS MUSEUM INC
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'c5bd4861-9cab-47a8-8fa6-b8047f746b21'; -- COLUMBUS OHIO FIREFIGHTERS MUSEUM INC
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '76c250df-4e9c-4563-968e-93f1af8a0985'; -- GANGA LIBRARY INC
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'aa24bf4a-6535-4764-a866-e7edb840713d'; -- Gift of Adoption Fund
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '3dda2496-6999-4b47-b47b-1199b303230b'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '7bf4681d-b250-4d1f-839b-1fe6c687f73b'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '7cc0972b-7db8-4b80-9f11-fdd1e414f22c'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'a71827b7-b312-4741-87a4-7edc44d19d6e'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'c80dfbe5-8e17-4a8e-bcaf-87eea29b6ddb'; -- Live Life With Purpose International, Inc
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'cd76bee6-1abc-4321-a2c2-658b2b082da9'; -- MagLiteracy
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'ff4edfc6-5489-4e27-bbb9-fac771207d1d'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '289f0b1b-7da8-4807-8c96-1712df1c3376'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'ddc140b3-3a3d-4213-b6d0-2609fc27983b'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '8192ca6a-5d18-48ea-be45-adb748e650ae'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '4d189927-9632-4795-9512-2d8e2d3cd7d7'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '265d2893-59e8-4f22-8d25-2013b54dbae2'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'f17ef536-2efc-4e7d-8804-7a69748b0eb5'; -- National Church Residences Hospice
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '091a28bf-ff79-4c96-9a73-3e693a7c0c5f'; -- OHIO ANIMAL ADVOCATES
update public.volunteer_opportunities set nac_event = 'November 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '82671c08-4528-4d50-b76d-f837aec516ff'; -- VITAS Healthcare of Columbus
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'e11cd9d4-ed9b-4714-b9de-b014aca11fed'; -- A Gift For Teaching
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '624adb70-3c03-4ba6-8d15-c9a56f6006cf'; -- AnB Education
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '56636d98-202a-499a-96ce-7333c54625b3'; -- AnB Education
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'dfd9073e-09da-4925-afd2-5243b7c9c3de'; -- Arab American Community Center of Florida
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '66d5f6bb-cfbc-451a-a077-cd74dd69410c'; -- Broward House Inc.
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '395a17e7-06a3-45d6-abc7-a1e4995b6b79'; -- Down Syndrome Foundation of Florida
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '8cb49641-914d-4011-8d46-68ab6f20e6d6'; -- Habitat for Humanity of Lake-Sumter, Florida
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'e194da40-a2dc-4b83-a443-82407d35271b'; -- Hair That Cares, Inc. / Hairline Illusions Cares
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '6aff7a61-44e5-478a-a1af-24d451be8d70'; -- Islamic Relief USA
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '39bcaaa6-8437-4650-b778-0b2af6d19f19'; -- Mothers'' Milk Bank of Florida
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '2935f0ca-1154-4550-a474-87afb08731fa'; -- NorthWest Student Exchange
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'a358dd22-f508-40d2-b7b6-ce5b0def3176'; -- Orange County Animal Services
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'c586344b-60a1-45e5-93b5-ce276914b487'; -- Orange County Animal Services
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '02127803-1bf3-437b-99d7-2f52d2b74870'; -- Orange County Animal Services
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '62ab8053-84ee-4660-9cf9-29d95ea56e3d'; -- Orange County Animal Services
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '1b2c3685-1327-4f06-92aa-7948360d176f'; -- Revelations II. Inc
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = 'a91b62bf-5cc9-4dc8-b870-d8d1608c06de'; -- SENIORS FIRST, Inc.
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '5fb1272d-ec84-4087-bfff-069fbe2108cd'; -- SENIORS FIRST, Inc.
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '902e0b5e-41d6-4f9f-8570-6135fbc35c49'; -- SENIORS FIRST, Inc.
update public.volunteer_opportunities set nac_event = 'October 2026 NAC', distance_from_venue = 'Distance unknown -- no verifiable street address on file' where id = '5b752b48-faa4-47e7-8aa2-f39e9fa2a84a'; -- You Thrive Florida
